apiVersion: v1
kind: Service
metadata:
  name: meetup-nginx-service
  namespace: meetup
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: meetup-nginx
  type: NodePort
