apiVersion: v1
kind: Service
metadata:
  name: meetup-app-service-active 
  namespace: meetupbg
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: meetup-app-prod

