apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: meetup-app-prod
  namespace: meetupbg
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: meetup-app-prod
  template:
    metadata:
      labels:
        app: meetup-app-prod
    spec:
      containers:
      - name: meetup-app-prod
        image: registry.hub.docker.com/arunvarghe/meetup:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
  strategy:
    blueGreen: 
      activeService: meetup-app-service-active
